dataset:
  root_npz: "/mnt/data/preprocess/preprocess"
  pretrain_json: "/mnt/data/split/split/latvia_vs_estonia/pretrain/region_split.json"
  pretrain_json_overlap: "/mnt/data/split/split/latvia_vs_estonia/pretrain/region_split_overlap.json"
  pretrain_json_lvpt: "/mnt/data/split/split/latvia_portugal_vs_estonia/pretrain/region_split.json"
  pretrain_json_lvpt_overlap: "/mnt/data/split/split/latvia_portugal_vs_estonia/pretrain/region_split_overlap.json"
  finetune_json_tpl: "/mnt/data/split/split/latvia_vs_estonia/finetune/split_k_strict/region_split_{k}.json"
  drop_b10: true
  normalize: "zscore"

pretraining:
  scenario: "LVPT_overlap"            # LV | LV_overlap | LVPT | LVPT_overlap
  batch_size: 128
  epochs: 150
  early_stopping_patience: 15
  lr: 3.0e-4
  cosine_anneal: {enabled: true, cycles: 1}
  downsample_meadow_to_median: true

finetune:
  k_grid: [1,5,10,20,100,200,500]
  batch_size: 16
  epochs: 200
  early_stopping_patience: 5
  lr_mode: "separate"       # head_only | same | separate
  lr:
    same: 3.0e-4
    head_only: 3.0e-4
    separate: {head: 3.0e-4, backbone: 1.0e-4}

encoder:
  dim: 256
  depth: 2
  dropout: 0.1

eval:
  seeds: [0,1,2,3,4]
  metrics: ["acc"]
paths:
  outputs_dir: "outputs/baseline_paper_LVPT_overlap"
