seed: 42
device: "cuda"
num_workers: 8

paths:
  outputs_dir: "outputs/lv_overlap_transformer"

dataset:
  name: "EuroCropsML"
  root_npz: "/mnt/data/preprocess/preprocess"
  pretrain_json: "/mnt/data/split/split/latvia_vs_estonia/pretrain/region_split.json"
  pretrain_json_overlap: "/mnt/data/split/split/latvia_vs_estonia/pretrain/region_split_overlap.json"  # <-- overlap-only LV (EE classes)
  pretrain_json_lvpt: "/mnt/data/split/split/latvia_vs_estonia/pretrain/region_lvpt.json"
  pretrain_json_lvpt_overlap: "/mnt/data/split/split/latvia_vs_estonia/pretrain/region_lvpt_overlap.json"
  finetune_json_tpl: "/mnt/data/split/split/latvia_vs_estonia/finetune/split_k_strict/region_split_{k}.json"
  drop_b10: true
  normalize: "zscore"

encoder:
  # tiny Transformer over time (CLS-pooled)
  dim: 256
  layers: 2
  nhead: 8
  ff_mult: 4
  dropout: 0.1
  max_len: 1024

pretraining:
  scenario: "LV"     # "LV", "LV_overlap", "LVPT", or "LVPT_overlap"
  batch_size: 128
  epochs: 150
  early_stopping_patience: 15
  lr: 3.0e-4
  weight_decay: 1.0e-4
  cosine_anneal: { enabled: true, cycles: 1 }   # per paper: ON for LV; set false for LVPT
  downsample_meadow_to_median: true
  meadow_label_id: null  # set numeric ID ONLY if your split JSON includes a pid->label map; else leave null

finetune:
  k_grid: [1,5,10,20,100,200,500]
  batch_size: 16
  epochs: 200
  early_stopping_patience: 5
  lr_mode: "separate"   # "separate" | "same" | "head_only"
  lr:
    same: 3.0e-4
    head_only: 3.0e-4
    separate:
      head: 3.0e-4
      backbone: 1.0e-4
  weight_decay: 1.0e-4
  cosine_anneal: { enabled: false }  # keep OFF unless you have evidence it helps for your scenario

eval:
  seeds: [0,1,2,3,4]
  metrics: ["acc"]

paths:
  outputs_dir: "outputs/exact_paper_LV"
